### ISSUE TITLE
Vagrantfile: box is not found

### ISSUE THREAD

**Issue by vladimir77** [mmuehlberger/tutsplus-vagrant-node#1]
Hello!

Unfortunately I cannot create VM from your Vagrantfile because the box "chef/ubuntu-14.04" is not exist on box repository https://atlas.hashicorp.com/search.

Thanks!

**Comment by mmuehlberger** [comment]
Hi,

sorry I didn't get back to you earlier.

Apparently they renamed their organization from chef to bento (the name of the project used to build all those boxes), and it is now under `bento/ubuntu-14.04`.

I hope this solves your issue.

**Comment by vladimir77** [comment]
Thanks!
